### PR TITLE
Added 'syslog_output' support.

### PR DESCRIPTION
**Pull request by bdwyertech**
I added 'syslog_output' support.  This can help out in a decentralized or dynamic environment, where you might have to use OSSEC in local mode, but want to ship alerts somewhere, without the complexity of agent mode or an OSSEC server.

FYI: OSSEC ships via UDP, so you might want to use rsyslog or nxlog locally to relay this reliably, via TCP. If you want to secure the transport as well, I'd  suggest NXlog's SSL output module.

### CODE REVIEW

**Comment by bdwyertech** [comment]
Any chance of this getting merged in at some point?

**Comment by bdwyertech** [comment]
Any chance of this getting merged in at some point?

**Comment by tas50** [comment]
Configs are now full configurable by the user.  The user can add syslog output without the need for additional attributes.  I'm going to close this out now.

**Comment by bdwyertech** [comment]
I would definitely give the next release a major version bump.  Lots has
changed from the looks of it. @tas50

**Pull request closed without merging**
